### ISSUE TITLE
Non-shareable fields coming from pagination

### ISSUE THREAD

**Issue by cosmin-techoff** [TriPSs/nestjs-query#106]
**Describe the bug**
I get the following errors when trying to create a federation graph:

	Non-shareable field "PageInfo.hasNextPage" is resolved from multiple subgraphs: it is resolved from subgraphs "orders" and "shipments" and defined as non-shareable in all of them
	Non-shareable field "PageInfo.hasPreviousPage" is resolved from multiple subgraphs: it is resolved from subgraphs "orders" and "shipments" and defined as non-shareable in all of them
	Non-shareable field "PageInfo.startCursor" is resolved from multiple subgraphs: it is resolved from subgraphs "orders" and "shipments" and defined as non-shareable in all of them
	Non-shareable field "PageInfo.endCursor" is resolved from multiple subgraphs: it is resolved from subgraphs "orders" and "shipments" and defined as non-shareable in all of them

Is there any way to add the directive to this type?

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

yes

**Expected behavior**
PageInfo type should have the @shareable directive

**Comment by TriPSs** [comment]
I have no experience with federation graphs, is this something you could checkout?

**Comment by detwait** [comment]
TriPSs any updates on that one ?

**Comment by cosmin-techoff** [comment]
#132

**Comment by TriPSs** [comment]
Since #132 is now merged/released I'm going to close this ticket.
