### ISSUE TITLE
Support @nestjs/graphql@11

### ISSUE THREAD

**Issue by MrSquaare** [TriPSs/nestjs-query#109]
**Is your feature request related to a problem? Please describe.**
@nestjs/graphql@11 has been released : https://github.com/nestjs/graphql/releases/tag/v11.0.0

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes

**Describe the solution you'd like**
Support @nestjs/graphql@11

**Comment by GP4cK** [comment]
@TriPSs in nest/graphql, [between 10.1.6 and 10.1.7](https://github.com/nestjs/graphql/compare/v10.1.6...v10.1.7), a change was introduced which make the graphql tests not independent.

I [asked for some help](https://discord.com/channels/520622812742811698/1093384149848555521/1093384149848555521) from the nestjs team but so far, we haven't managed to come up with a solution.

Actually, even today, the tests are not super clean. For example, if you look at the snapshot for the test one read relation: https://github.com/TriPSs/nestjs-query/blob/ae981282da56332f258ca3ddf150d35516098886/packages/query-graphql/__tests__/resolvers/relations/read-relation.resolver.spec.ts#L40

The snapshot is:
https://github.com/TriPSs/nestjs-query/blob/ae981282da56332f258ca3ddf150d35516098886/packages/query-graphql/__tests__/resolvers/relations/__snapshots__/read-relation.resolver.spec.ts.snap#L995-L1043

Which still includes `TestRelationDTOEdge`, `ConnectionCursor` although there are not used in the schema.

I think that if we wrap the class definitions in a function, then it will fix this issue. How about I make a first PR without touching the dependencies, just to refactor the tests and the snippets, and then another one to upgrade nestjs/graphql? Do you agree with this approach?

**Comment by TriPSs** [comment]
@GP4cK would appreciate that! Thanks for the help!
