### ISSUE TITLE
OnBefore and UpdateDateColumn on base classes no longer fire

### ISSUE THREAD

**Issue by coupster74** [TriPSs/nestjs-query#114]
**Describe the bug**
This recently worked while using the Doug Martin code base. After migrating to TriPSs, it no longer does. I have a base class with updated:DateTime annotated with UpdateDateColumn, and OnBefore attributes. When saving entities which extend the base class, these no longer fire. 

Here is the base class: 
`import { PrimaryGeneratedColumn, Column } from 'typeorm';
import { GraphQLISODateTime, ID, ObjectType } from '@nestjs/graphql';
import { FilterableField, IDField } from '@ptc-org/nestjs-query-graphql';
import { CommonFields } from './common-fields.entity';

@ObjectType()
export abstract class BaseEntity extends CommonFields {
  @IDField(() => ID)
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @FilterableField(() => GraphQLISODateTime)
  @Column({ type: 'timestamp', nullable: true })
  remoteUpdated?: Date;
}`

Here is the intermediate class: 
`import {
  Column,
  UpdateDateColumn,
  CreateDateColumn,
  Index,
  DeleteDateColumn,
} from 'typeorm';
import { Field, GraphQLISODateTime, ObjectType } from '@nestjs/graphql';
import {
  BeforeCreateMany,
  BeforeCreateOne,
  BeforeUpdateMany,
  BeforeUpdateOne,
  CreateManyInputType,
  CreateOneInputType,
  FilterableField,
  UpdateManyInputType,
  UpdateOneInputType,
} from '@ptc-org/nestjs-query-graphql';
import { UserContextOnRequest } from '../../auth/user-context.interface';

@ObjectType()
@BeforeCreateOne(
  (input: CreateOneInputType<CommonFields>, context: UserContextOnRequest) => {
    console.log('BeforeCreateOne');
    // eslint-disable-next-line no-param-reassign
    const createdBy = context.req.user?.userContext
      ? context.req.user?.userContext.email
      : 'Unknown';
    return {
      input: { ...input.input, createdBy: createdBy, updatedBy: createdBy },
    };
  },
)
@BeforeCreateMany(
  (input: CreateManyInputType<CommonFields>, context: UserContextOnRequest) => {
     console.log('BeforeCreateMany');
    const createdBy = context.req.user?.userContext
      ? context.req.user?.userContext.email
      : 'Unknown';
    // eslint-disable-next-line no-param-reassign
    input.input = input.input.map((c) => ({
      ...c,
      createdBy,
      updatedBy: createdBy,
    }));
    return input;
  },
)
@BeforeUpdateOne(
  (input: UpdateOneInputType<CommonFields>, context: UserContextOnRequest) => {
         console.log('BeforeUpdateOne');
    // eslint-disable-next-line no-param-reassign
    const updatedBy = context.req.user?.userContext
      ? context.req.user?.userContext.email
      : 'Unknown';
    input.update.updatedBy = updatedBy;
    return input;
  },
)
@BeforeUpdateMany(
  (
    input: UpdateManyInputType<CommonFields, CommonFields>,
    context: UserContextOnRequest,
  ) => {
    console.log('BeforeUpdateMany');
    const updatedBy = context.req.user?.userContext
      ? context.req.user?.userContext.email
      : 'Unknown';
    // eslint-disable-next-line no-param-reassign
    input.update.updatedBy = updatedBy;
    return input;
  },
)
export abstract class CommonFields {
  @FilterableField({ defaultValue: true })
  @Column({ type: 'boolean', default: true })
  isActive: boolean;

  @FilterableField({ defaultValue: false })
  @Column({ type: 'boolean', default: false })
  isArchived: boolean;

  @FilterableField({ nullable: true })
  @Column({ type: 'varchar', nullable: true })
  @Index({ fulltext: true })
  internalComment?: string;

  @FilterableField(() => GraphQLISODateTime)
  @CreateDateColumn({ type: 'timestamp' })
  created: Date;

  @FilterableField({ nullable: true })
  @Column({ type: 'varchar', nullable: true })
  @Index()
  createdBy: string;

  @FilterableField(() => GraphQLISODateTime)
  @UpdateDateColumn({ type: 'timestamp' })
  updated: Date;

  @FilterableField({ nullable: true })
  @Column({ type: 'varchar', nullable: true })
  updatedBy: string;

  @Field(() => GraphQLISODateTime, { nullable: true })
  @DeleteDateColumn({ type: 'timestamp', nullable: true })
  deletedOn?: Date;

  @FilterableField({ nullable: true })
  @Column({ type: 'varchar', nullable: true })
  deletedBy: string;
}
`

here is the end class: 
`import { FilterableField, QueryOptions } from '@ptc-org/nestjs-query-graphql';
import { Field, ObjectType, registerEnumType } from '@nestjs/graphql';
import { DEFAULT_QUERY_RESULTS } from '../config/constants';
import { Entity, Column, Index } from 'typeorm';
import { BaseEntity } from './base/base.entity';

export enum ActivityLogType {
  EMAIL_DAILY = 'EMAIL-DAILY',
  EMAIL_SUB_CHECK = 'EMAIL-SUB-CHECK',
  SYNC_AGENT_PP = 'SYNC-PP',
  SEARCH = 'SEARCH',
  MUTATION = 'MUTATION',
  AUTHENTICATION = 'AUTHENTICATION',
  QUERY = 'QUERY',
  API = 'API',
  EXCEL = 'EXCEL',
}

registerEnumType(ActivityLogType, {
  name: 'ActivityLogType',
  description: 'Activity Log Types',
});

@Entity()
@ObjectType()
@QueryOptions({ defaultResultSize: DEFAULT_QUERY_RESULTS, maxResultsSize: -1 })
export class ActivityLog extends BaseEntity {
  @FilterableField(() => ActivityLogType, { nullable: false })
  @Column({ nullable: false })
  @Index()
  type!: ActivityLogType;

  @Field({ nullable: true })
  @Column({ nullable: true })
  details?: string;

  @FilterableField({ nullable: true })
  @Column({ nullable: true })
  @Index()
  referenceEntity?: string;

  @FilterableField({ nullable: true })
  @Column({ nullable: true })
  @Index()
  referenceId?: string;
}
`

and now when I attempt a createOneEntity for an Entity based on this, the return error is: 
`[GraphQL error]: Message: Variable "$input" got invalid value { type: "EMAIL_DAILY", details: "" } at "input.activityLog"; Field "created" of required type "DateTime!" was not provided., Location: [object Object], Path: undefined
[GraphQL error]: Message: Variable "$input" got invalid value { type: "EMAIL_DAILY", details: "" } at "input.activityLog"; Field "id" of required type "ID!" was not provided., Location: [object Object], Path: undefined
[GraphQL error]: Message: Variable "$input" got invalid value { type: "EMAIL_DAILY", details: "" } at "input.activityLog"; Field "remoteUpdated" of required type "DateTime!" was not provided., Location: [object Object], Path: undefined
[GraphQL error]: Message: Variable "$input" got invalid value { type: "EMAIL_DAILY", details: "" } at "input.activityLog"; Field "updated" of required type "DateTime!" was not provided., Location: [object Object], Path: undefined`

**Expected behavior**
when saving the final entity, the default values or set values from annotations in ancestor classes fire as required to set the values. Again, this use to work with Doug Martin's version of the framework

Any ideas?

**Comment by TriPSs** [comment]
Well if I see your error correctly you are getting this `Message: Variable "$input" got invalid value` that values are missing, is is graphql validating, which is changed in #78 to require all fields (as that is also expected when creating).

**Comment by coupster74** [comment]
Ah.. I think I understand what you mean. I'll play around with this and confirm.

**Comment by coupster74** [comment]
@TriPSs you were absolutely correct. Adjusting the schema to support nullable fixed the issue. thanks!
