### ISSUE TITLE
Some kind of cache was introduced in [10.1.7](https://github.com/nestjs/graphql/releases/tag/v10.1.7) which makes the graphql tests fail as they are no longer independent.

### ISSUE THREAD

**Issue by TriPSs** [TriPSs/nestjs-query#119]
> Some kind of cache was introduced in [10.1.7](https://github.com/nestjs/graphql/releases/tag/v10.1.7) which makes the graphql tests fail as they are no longer independent.
The simplest example I found is here: https://github.com/TriPSs/nestjs-query/blob/ae981282da56332f258ca3ddf150d35516098886/packages/query-graphql/__tests__/resolvers/relations/read-relation.resolver.spec.ts#L40-L43
>
>If you run both of these tests one by one, they pass. However, together, the second will fail because the `TestResolverDTO` will still have the default relation that was created in the first one.
>
>If you want, I could also pin it to 10.1.6.
>
>Next, I'd like to work on upgrading to graphql 11, because that's what is required to run the [dev tools](https://docs.nestjs.com/devtools/overview) and I would really like that.
>
>_Originally posted by @GP4cK in https://github.com/TriPSs/nestjs-query/pull/118#discussion_r1161387079_

Created this ticket so we can check this out and others can see why potentially some of their tests are failing of they update this dep.

**Comment by GP4cK** [comment]
Adding link to the discord discussion with the NestJS team:
https://discord.com/channels/520622812742811698/1093384149848555521/1093384149848555521

**Comment by TriPSs** [comment]
I don't see any issues with splitting it, if that makes it work again we can do that!
