### ISSUE TITLE
@ptc-org/nestjs-query-sequelize package is missing some files.

### ISSUE THREAD

**Issue by Yiin** [TriPSs/nestjs-query#12]
**Describe the bug**
@ptc-org/nestjs-query-sequelize built package doesn't contain all the required files for it to function.
```
Error: Cannot find module './services'
Require stack:
- /<path to project>/server/node_modules/@ptc-org/nestjs-query-sequelize/src/index.js
```

**To Reproduce**
1. Install @ptc-org/nestjs-query-sequelize package
2. Include it.

"@ptc-org/nestjs-query-sequelize": "^1.0.0-alpha.1",

**Comment by TriPSs** [comment]
Could you try `@ptc-org/nestjs-query-sequelize@1.0.0-alpha.2`?

**Comment by Yiin** [comment]
Thanks! ❤️
