### ISSUE TITLE
Nested filtering doesn't work

### ISSUE THREAD

**Issue by detwait** [TriPSs/nestjs-query#121]
For one of my responses I've created @FilterableUnPagedRelation('trackUsers')

But when I tried filter by userId from that relation

{
  getTracks(filter: {
    trackUsers: {
      userId: { eq: "some uuid" }
    }
  }) {
    nodes {
      id
    }
  }
}

I received:
"Error: unknown operator \"userId\"",
            "    at SQLComparisonBuilder.build (C:\\projects_unitea\\unitea-backend-ms-media\\packages\\query-typeorm\\src\\query\\sql-comparison.builder.ts:90:11)",

It it like library try to parse filterabled field as operator.

**Comment by GP4cK** [comment]
This is not supported at the moment. Here's a link to a workaround in the original repo:
https://github.com/doug-martin/nestjs-query/issues/805#issuecomment-1372861324
