### ISSUE TITLE
Support for mongoose v6

### ISSUE THREAD

**Issue by Michael-M-Judd** [TriPSs/nestjs-query#15]
### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

**Describe the solution you'd like**
Upgrade the peerDependency from mongoose v5 to v6. I've tested it with the majority of features and it seems to be working as-expected.
**Describe alternatives you've considered**
It uses the mongoDB driver v4, so that is something to consider. Looking at the breaking changes I don't think we use much of what's there: https://mongoosejs.com/docs/migrating_to_6.html

If we're comfortable moving the project to v6, I'm happy to take it on.

**Comment by TriPSs** [comment]
Sorry for the late reply, I think we can do this since the `mongoose` inside the root package.json is also 6 now.

**Comment by GP4cK** [comment]
Now it's even 7.0.3. I think we can close this issue.
