### ISSUE TITLE
Publish v3.0.0 to NPM

### ISSUE THREAD

**Issue by YeomansIII** [TriPSs/nestjs-query#152]
v3.0.0 is not published to NPM.js

Not sure if this was missed or it's still in processing.

**Comment by TriPSs** [comment]
I see that it was a bug in actions, it bumped everything but did not thing anything was changed so skipped building/publishing. 

Will do it manual, apologies!

**Comment by YeomansIII** [comment]
No worries, thank you TriPSs. Appreciate all that you do for this project. I know it hasn't been too long since you took over as maintainer, but if you are willing to accept a "coffee" or monetary contribution for your efforts I would love to contribute. In any case, thanks again.
