### ISSUE TITLE
nestjs-query does not work with nestjs v10

### ISSUE THREAD

**Issue by ybjeon01** [TriPSs/nestjs-query#158]
**Describe the bug**

I tried to follow the example in the document page, but when installing dependencies, npm complains that it is unable to resolve dependency tree.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nestjs-query-getting-started@0.0.1
npm ERR! Found: @nestjs/common@10.1.0
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^10.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^8.0.4" from @nestjs-query/query-graphql@0.30.0
npm ERR! node_modules/@nestjs-query/query-graphql
npm ERR!   @nestjs-query/query-graphql@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/ybjeon01/.npm/_logs/2023-07-24T06_18_20_004Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/ybjeon01/.npm/_logs/2023-07-24T06_18_20_004Z-debug-0.log
```

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

yes

**To Reproduce**
1. npm i -g @nestjs/cli
2. nest new nestjs-query-getting-started
3. npm i @nestjs-query/query-graphql @nestjs/common @nestjs/graphql graphql graphql-subscriptions class-transformer class-validator dataloader

**Expected behavior**

It should install all dependencies without problems.

**Screenshots**
![image](https://github.com/TriPSs/nestjs-query/assets/16087578/2888fc34-ec02-4446-929b-407d4bc99fe0)

**Desktop (please complete the following information):**
 - Node Version [v 18.16.0]
 - Nestjs-query Version [e.g. v0.21.0]

**Additional context**
no additional context

**Comment by smolinari** [comment]
You are using the wrong packages.

https://tripss.github.io/nestjs-query/docs/introduction/install

Scott

**Comment by ybjeon01** [comment]
Thank you for the quick reply. If TypeOrm and GraphQL are all I want to use, Is installing @ptc-org/nestjs-query-typeorm enough?

It was a bit confusing when reading the installation documentation as there were 6 different installation commands.
If you don't mind, where can I find documentation showing the difference between the core package and the graphql package?

**Comment by TriPSs** [comment]
If you want to use TypeORM and GrapQL you should install the following packages:
```
// Core, always needed
@ptc-org/nestjs-query-core @nestjs/common class-transformer
// GraphQL packages
@ptc-org/nestjs-query-graphql @nestjs/common @nestjs/graphql graphql graphql-subscriptions class-transformer class-validator dataloader
// Typeorm
@ptc-org/nestjs-query-typeorm @nestjs/common @nestjs/typeorm class-transformer typeorm
```

I completely agree with you that this is very unclear, will mark this ticket as documentation so we can update it. I also doubt all these packages are needed as some are also as dependencies of the packages it self.

**Comment by ybjeon01** [comment]
Thank you! The dependency problem is resolved. Actually, I tried to mimic the dependency problem again to give more detail, but it does not happen again.

**Comment by TriPSs** [comment]
Closing as this will be done with #140
