### ISSUE TITLE
CRUDResolver "incorrectly extends base class"

### ISSUE THREAD

**Issue by YeomansIII** [TriPSs/nestjs-query#164]
**Describe the bug**
```
Class 'EventResolver' incorrectly extends base class 'CRUDResolver<EventDto, CreateEvent, UpdateEvent, Omit<ReadResolverOpts<EventDto>, "pagingStrategy"> & { ...; }, QueryService<...>>'.
  The types of 'service.query' are incompatible between these types.
    Type '(query: Query<EventEntity>, opts?: QueryOptions<EventEntity> | undefined) => Promise<EventEntity[]>' is not assignable to type '(query: Query<EventDto>, opts?: QueryOptions<EventDto> | undefined) => Promise<EventDto[]>'.
```

It looks like the generic type for QueryService in the CRUDResolver uses the DTO class, when the QueryService, according to the docs, should be using the Entity class. Should I change my QueryService to use the DTO class? When I do change my QueryService to the DTO class, I get another error where Nestjs cannot find the service "EventDtoQueryService", obviously because the auto-generated query service is using the name "EventEntityQueryService".

What's the appropriate solution to this, or is this a bug?

** I have strict TypeScript rules enforcement enabled **

I am getting similar errors when using a custom service. The following custom service, causes an identical error in the TaskResolver CRUDResolver class:
```
@QueryService(TaskEntity)
export class TaskService extends TypeOrmQueryService<TaskEntity> {
  constructor(@InjectRepository(TaskEntity) repo: Repository<TaskEntity>) {
    super(repo);
  }

. . .
```

Thanks.

**To Reproduce**
1. Enable **strict** TypeScript rules
2. Create simple module with EventEntity, EventDto, and EventResolver.
3. EventResolver should be a CRUDResolver for the EventDto class, using the EventEntity QueryService
4. VsCode shows errors.

**Expected behavior**
QueryService<EventEntity> should not throw errors with a CRUDResolver<EventDto>

**Screenshots**
```javascript
@Resolver(() => EventDto)
export class EventResolver extends CRUDResolver(EventDto, {
  guards: [GqlSharedSecretAndJwtAuthGuard],
  CreateDTOClass: CreateEvent,
  UpdateDTOClass: UpdateEvent,
  enableAggregate: true,
}) {
  constructor(@InjectQueryService(EventEntity) readonly service: QueryService<EventEntity>) {
    super(service);
  }
}
```

```javascript
@Module({
  imports: [
    EventEntityModule,
    NestjsQueryGraphQLModule.forFeature({
      imports: [NestjsQueryTypeOrmModule.forFeature([EventEntity])],
      dtos: [{ CreateDTOClass: CreateEvent, UpdateDTOClass: UpdateEvent, DTOClass: EventDto }],
    }),
  ],
  providers: [EventResolver],
  controllers: [EventsController],
  exports: [NestjsQueryGraphQLModule],
})
export class EventsModule {}
```

**Desktop (please complete the following information):**
 - Node Version 20.5.0
 - Nestjs-query Version 4.0.0
 - Typescript 5.1.6

**Comment by TriPSs** [comment]
Could you share the complete error? The only times that I got those was because in the DTO I had for exampe `field: string` while in the entity it was `field?: string`.
