### ISSUE TITLE
Adding Federation v2 Example to nestjs-query - Collaboration Inquiry

### ISSUE THREAD

**Issue by meekdenzo** [TriPSs/nestjs-query#166]
I'm interested in contributing to the library by adding an example implementation for Federation v2. Currently, only Federation v1 is shown, and I believe having a Federation v2 example would be beneficial.

I'd like to know if there are any ongoing efforts to add a Federation v2 example. I'm eager to collaborate and combine our efforts if others are already working on this.

**Comment by TriPSs** [comment]
Would be awesome if you could add it, I myself do not use federation so have not looked at those code parts.

**Comment by meekdenzo** [comment]
Cool, I'll jump on it!

**Comment by meekdenzo** [comment]
@TriPSs Sorry for the long wait on this. I had to work on the federation v2 example from a new [repo](https://github.com/meekdenzo/nestjs-query-federation) before adding it here. Happy to report that it's now working without any issues. I'll submit the PR once all the tests pass.

_PS. My stack (at my job) uses MongoDB/Mongoose, but I'm still having challenges with the implementation in federation (hence the delay in delivery here)._

**Comment by meekdenzo** [comment]
Added https://github.com/TriPSs/nestjs-query/pull/189
