### ISSUE TITLE
FilterableField not recognizing name in options

### ISSUE THREAD

**Issue by fabianboerner** [TriPSs/nestjs-query#169]
I have the follwing:

```ts
@FilterableField({name: 'jobReferenceNumber'})
  'Job Reference Number'?: string;
```

And getting the following error:

/app/node_modules/graphql/type/assertName.js:31
      throw new _GraphQLError.GraphQLError(
            ^
GraphQLError: Names must only contain [_a-zA-Z0-9] but "Job Reference Number" does not.

**To Reproduce**
1. create graphql module
2. use spaces in name 

**Expected behavior**
Name is used as actual name, as working for @Field decorator

**Comment by TriPSs** [comment]
Can you test with `@ptc-org/nestjs-query-graphql@4.2.1-alpha.1`
