### ISSUE TITLE
Filterable nested object in mongoose

### ISSUE THREAD

**Issue by iamkhalidbashir** [TriPSs/nestjs-query#180]
I could not find a way to make a property filterable for a sub-object of mongoose document. Only root properties seems to be filterable

**Comment by TriPSs** [comment]
Sub objects that can be filtered need to be defined with [`FilterableRelation`](https://tripss.github.io/nestjs-query/docs/graphql/relations) for example, think in Mongoose this is maybe not always a actual relation but you can try that.

**Comment by iamkhalidbashir** [comment]
![Screenshot from 2023-09-20 19-21-57](https://github.com/TriPSs/nestjs-query/assets/27646811/aa41be57-fbd4-4493-9ae0-47ae7cb3960f)

So is this warning in docs outdated?

**Comment by TriPSs** [comment]
No, that is probably correct.

I do not use mongoose so I do not know those parts.

**Comment by smolinari** [comment]
Using dot notation didn't work?

Scott

**Comment by iamkhalidbashir** [comment]
Yes it did work, thanks.

**Comment by TriPSs** [comment]
Going to close this issue as it's resolved.

**Comment by iamkhalidbashir** [comment]
Actually its giving this error when call api call

Looks like it could not find a reference model, but there should be no reference model to search for as its a sub object

```
Error: Unable to lookup reference type for template"
1
: 
"    at MongooseQueryService.getReferenceModel (/home/node/app/packages/query-mongoose/src/services/reference-query.service.ts:339:11)"
2
: 
"    at MongooseQueryService.getReferenceQueryBuilder (/home/node/app/packages/query-mongoose/src/services/reference-query.service.ts:320:45)"
3
: 
"    at MongooseQueryService.findRelation (/home/node/app/packages/query-mongoose/src/services/reference-query.service.ts:138:40)"
4
: 
"    at /home/node/app/packages/query-graphql/src/loader/find-relations.loader.ts:34:47"
```

**Comment by iamkhalidbashir** [comment]
> Using dot notation didn't work?

Could you please elaborate?
Dot notation using where?

I tried this, where whould I put dot notation?
![image](https://github.com/TriPSs/nestjs-query/assets/27646811/d351ecc5-cde4-4b87-8892-019b3825f24b)

**Comment by iamkhalidbashir** [comment]
I see this "Virtual relations"
Should this be the solution for now ?
![image](https://github.com/TriPSs/nestjs-query/assets/27646811/5d87b078-bf99-4d34-8239-8e2e4c563c92)
