### ISSUE TITLE
RelationsInput is not known

### ISSUE THREAD

**Issue by Angeloem** [TriPSs/nestjs-query#182]
**Describe the bug**
From this [link](https://tripss.github.io/nestjs-query/docs/graphql/relations#unpagedrelation) of the documentation, when working with unpaged relations, it expects an input of type **RelationsInput**.
That was working fine, but after upgrading from the deprecated package to this, RelationsInput is not understood by the package.

I get this error: "Unknown type "RelationsInput". Did you mean "LocationInput"?"

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

I just did.

**To Reproduce**
1. Create a class with its children and wait for the schema to be generated.
    - In the generated schema, RelationsInput won't be there, there will be a class called AddChildrenToParent | SetChildrenToParent
 
**Expected behavior**
A RelationsInput should be created as per the docs on this [link](https://tripss.github.io/nestjs-query/docs/graphql/relations#unpagedrelation).

**Screenshots**

**Desktop (please complete the following information):**
 - Node Version [e.g. 16.20.1]
 - Nestjs-query Version [e.g. ^3.0.2]

**Additional context**

**Comment by TriPSs** [comment]
Please see [v2.x.x-to-v3.x.x](https://tripss.github.io/nestjs-query/docs/migration-guides/v2.x.x-to-v3.x.x)

**Comment by Angeloem** [comment]
I've done this @TriPSs,

Let me share my screenshots.
<img width="655" alt="Screenshot 2023-09-22 at 11 36 48" src="https://github.com/TriPSs/nestjs-query/assets/40020525/7d524b51-42fd-46f9-8e32-b7830967ac6a">

**Comment by TriPSs** [comment]
I don't see the issue? `AddProductsToCampaignInput` === `RelationsInput ` but with a different name? All of these get there own version (this is also not changed between this fork and the original)

**Comment by Angeloem** [comment]
I understand you. 

But I ended up custom editing the names to fit the scenario.

I don't think it's good though.
