### ISSUE TITLE
Authorization improvement

### ISSUE THREAD

**Issue by tonytoth** [TriPSs/nestjs-query#19]
Im trying to build an authorization system using ```nestjs-query``` but I found a limitation.
e.g: Im trying to check if a user has access to some products.
Say you have a query like this:
```
query getProducts {
  products(filter: { id: { in: [1,2,3] } }) {
    id
  }
}
```
but the user only has access to product 1,2 so I want to call a service to check this but I am not able to read query / mutation args because ```AuthorizationFilter``` is sending the ```ExecutionContext```, not the ```GqlExecutionContext```.
I think the issues is here: https://github.com/doug-martin/nestjs-query/blob/v0.27.0/packages/query-graphql/src/decorators/authorize-filter.decorator.ts#L10

Unfortunately I am still using v0.27 and there is a long way to go untill I can upgrade to v0.30. Meanwhile I will use Guards to solve this issue.

**Comment by TriPSs** [comment]
I think what you want can be achieved with a [custom authorizer](https://tripss.github.io/nestjs-query/docs/graphql/authorization#custom-authorizer).

Could you also elaborate why you are still using the older version?

**Comment by tonytoth** [comment]
I can't do that, because I need to get the args for graphql and I can't get those from ExecutionContext.

Using the older version because there are few breaking changes as far as I know and I have few custom resolvers and many workarounds.

**Comment by TriPSs** [comment]
I'm not quite sure why you would need to read the args, as if the data is filtered that it only returns id 1 and 2 the user can try to retrieve it but it won't never return id 3.

Aldo I have to say that this probably wont work with the version you have as there was a bug that cased auth filter and provided filter to not be merged correctly causing the provided filter to overwrite the field that was in the auth filter.

I'm not quite sure I can help you here, sorry.

**Comment by tonytoth** [comment]
Well, you can call this API using Postman and do this query: 
```
query getProducts {
  products(filter: { id: { in: [1,2,3] } }) {
    id
  }
}
```
Right ?
Now I need to check, do you have rights to read all these 3 products ?
How can I do this ?

**Comment by TriPSs** [comment]
Well like I said, in the latest version I would (and in my project do) use a [custom authorizer](https://tripss.github.io/nestjs-query/docs/graphql/authorization#custom-authorizer).

For a custom authorizer you don't need an custom resolver.

**Comment by tonytoth** [comment]
I would do that too, but you still need to read those args, don't you ?

**Comment by TriPSs** [comment]
Nope, if for example your products have a `userId` field which makes sure the user only has access to those products the custom authorizer would look like this
```
@Injectable()
export class SubTaskAuthorizer implements CustomAuthorizer<SubTaskDTO> {
 public  authorize(context: UserContext): Promise<Filter<SubTaskDTO>> {
    return {
      userId: { eq: context.req.user.id }
    }
  }
}

```

**Comment by tonytoth** [comment]
Well, this would work if you can filter relations with ```nestjs-query``` as I have the userId on a different table.

**Comment by TriPSs** [comment]
You can, if the relation is also defined with the decorators of `nestjs-query` you can add those like for example `info` is a relation here:

```
{
  info: {
   userId: { eq: context.req.user.id }
  }
}
```

**Comment by tonytoth** [comment]
Does this also work for many-to-many ?

**Comment by TriPSs** [comment]
Yes all relations.

**Comment by tonytoth** [comment]
Mmmmm, I am not sure how can I achieve this using Typeorm. I see example for [Mongoose](https://doug-martin.github.io/nestjs-query/docs/persistence/services#) but I can't find somethig for Typeorm.

**Comment by TriPSs** [comment]
This works with Typeorm as I also use that :) 

Just make sure that your Graphql definitions have the any of the `@Relation` definition and then it should work.

**Comment by tonytoth** [comment]
Aight, and for mutations does it work aswell ? I am not sure how it works here. It happens a transactions and it fails if it cannot query using this filter ?

**Comment by TriPSs** [comment]
Uhmm, I think in the old version it would return just `null`, this also works for mutations yes.

**Comment by tonytoth** [comment]
Do you also know if it works on multiple levels ? products -> test1 -> test2 -> test3 ? So I am trying to query something on test3 but I need to check if it has access to products ?

**Comment by TriPSs** [comment]
As far as I know that will work yes, aslong as all the relation types also have the auth decorator around then.

**Comment by tonytoth** [comment]
Aight, thank you very much for your help !
