### ISSUE TITLE
typeform prefix column with graphql filter

### ISSUE THREAD

**Issue by whoruyh** [TriPSs/nestjs-query#191]
When using a 'prefix: true' column in a typeform
How to use it in graphql filter?

Example
![image](https://github.com/TriPSs/nestjs-query/assets/52905766/93cce5e6-ba9f-471c-a705-3e88659727ea)
![image](https://github.com/TriPSs/nestjs-query/assets/52905766/429e63f7-f654-44a5-91f8-76793150ae8d)

The way you want it
`{
	"filter": {
		"bodySize": {
			"weight": {
				"lte": 20
			}
		}
	}
}`

`throw Error
Error: unknown operator "weight"
`

**Comment by TriPSs** [comment]
I have no idea what `prefix: true` does in TypeORM, could you elaborate a bit?

**Comment by TriPSs** [comment]
Closing, if still an issue please reopen.
