### ISSUE TITLE
how to best import modules to leverage custom services?

### ISSUE THREAD

**Issue by coupster74** [TriPSs/nestjs-query#206]
Might be a newby question, but I've been fighting with this for a while and didn't see any documentation on the best approach, or if it is even possible. 

I have two modules, action, which represents and entity, and clean up which performs clean up functions (like merging a related dimension) for many entities, including action.

In action, I wanted to use soft deletes, so I implemented an ActionService and ActionResolver which extends the CRUDResolver as below: 
```ts 
export class ActionResolver extends CRUDResolver(Action) {
...
```
with the following module definition: 
```ts
@Module({
  providers: [ActionResolver, GraphQLClientService],
  imports: [
    NestjsQueryGraphQLModule.forFeature({
      // import the NestjsQueryTypeOrmModule to register the entity with typeorm
      // and provide a QueryService
      imports: [
        NestjsQueryTypeOrmModule.forFeature([Action]),
      ],
      services: [ActionService],
      // describe the resolvers you want to expose
      resolvers: [
        {
          DTOClass: Action,
          EntityClass: Action,
          ServiceClass: ActionService,
          enableAggregate: true,
          enableSubscriptions: true,
          enableTotalCount: true,
        },
      ],
    }),
  ],
})
export class ActionModule {}
```

In the clean up module, I have been importing the dynamic .forFeature as show below. 

```ts 
@Module({
  imports: [
    NestjsQueryGraphQLModule.forFeature({
      imports: [
        ...
        NestjsQueryTypeOrmModule.forFeature([Action]),
        ... (plus many other .forFeatures)
      ],
    }),
  ],
  providers: [CleanUpResolver],
})
export class CleanUpModule {}
```
and was importing into the resolver via: 
```ts
constructor(
@InjectQueryService(Action)
    readonly actionService: QueryService<Action>, 
    ...(plus many other similar statements))
```

with my custom ActionService, this causes an issue where there are multiple DeleteResponse types for Action:
```
Error: Schema must contain uniquely named types but contains multiple types named "ActionDeleteResponse". 
```

I'm assuming this is because both my ActionModule and now the CleanUpModule are both declaring the same types for Action and that the best approach to resolve this is to import the ActionModule into the CleanUpModule so that the ActionService is still usable? Or is this a defect? It's interesting it isn't complaining about other types (but perhaps this is just the first one)? 

I can't seem to explicitly export ActionService from the ActionModule, nor does below work in CleanUpModule
```ts
    @Inject()
    readonly actionService: ActionService,
```
as it results in: 
```
Nest can't resolve dependencies of the CleanUpResolver (..., ?, ...). Please make sure that the argument dependency at index [8] is available in the CleanUpModule context.

Potential solutions:
- Is CleanUpModule a valid NestJS module?
- If dependency is a provider, is it part of the current CleanUpModule?
- If dependency is exported from a separate @Module, is that module imported within CleanUpModule?
  @Module({
    imports: [ /* the Module containing dependency */ ]
  }) 
```

**Comment by TriPSs** [comment]
I have bit of trouble understanding, but noticed the following:
When extending the `CrudResolver` you should not use the same one with `resolvers` inside the module, but use `dtos` instead, see [here for more info](https://tripss.github.io/nestjs-query/docs/graphql/resolvers#crudresolver:~:text=Notice%20how%20the%20dtos%20property%20is%20specified%20instead%20of%20the%20resolvers%2C%20this%20allows%20you%20to%20specify%20your%20DTOClass%2C%20CreateDTOClass%2C%20and%20UpdateDTOClass%20without%20creating%20an%20auto%2Dgenerated%20resolver.)
