### ISSUE TITLE
Add Fuzzy Search Support using fuse.js

### ISSUE THREAD

**Issue by abdelrahman-essawy** [TriPSs/nestjs-query#210]
### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?
yes

**Describe the solution you'd like**
Integrate fuse.js for fuzzy search, allowing users to find results even with typos or variations in search terms.

**Describe alternatives you've considered**
Considering fuse.js as a decent library for fuzzy search.

**Comment by TriPSs** [comment]
Search is handled by the docusaurus algolia plugin.
