### ISSUE TITLE
Option to disable pluralization of relation name

### ISSUE THREAD

**Issue by selvinkuik** [TriPSs/nestjs-query#217]
When implementing a `@FilterableUnPagedRelation` as documented here...

https://tripss.github.io/nestjs-query/docs/graphql/relations#filterableunpagedrelation

If you were to use the line...

`@FilterableUnPagedRelation('contentSent', () => SubTaskDTO, { update: { enabled: true } })`

The name is automatically pluralized, meaning the GQL query looks like this...

```gql
{
  parent {
    contentSents {
      ...
    }
  }
}
```

Requesting an option to be able to disable pluralization

**Comment by TriPSs** [comment]
Interesting, there is indeed something to say to never pluralize that name since if the name does not match the relation there already is an option to overwrite that (`relationName` option)

**Comment by TriPSs** [comment]
It's also bit weird that it does respect that name in the filters but than outputs it different in the query.
