### ISSUE TITLE
Nest can't resolve dependencies of the MarkdownActivityAuthorizerInterceptor

### ISSUE THREAD

**Issue by xin-ze** [TriPSs/nestjs-query#231]
**Describe the bug**

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes

**To Reproduce**
1. clone the small reproducible demo repository: [https://github.com/xin-ze/nestjs_reproduction/tree/main](https://github.com/xin-ze/nestjs_reproduction/tree/main)
2. select 'main' branch
3. refer to README.md and execute the code, will encounter an error: nestjs cannot find the generated AuthorizerProviders

**Expected behavior**
This error disappears

**Screenshots**
<img width="1649" alt="image" src="https://github.com/TriPSs/nestjs-query/assets/16400882/b2978d3e-4063-4d22-817a-ed8c7f0fd56e">

code path: apps/content/src/app/markdown/markdown.module.ts
<img width="1162" alt="image" src="https://github.com/TriPSs/nestjs-query/assets/16400882/c29fccb1-506f-481d-8f82-e07ac2f4403b">

**Desktop (please complete the following information):**
 - Node Version:  18.16.0
 - Nestjs-query Version v5.0.0

**Comment by TriPSs** [comment]
Please follow the [docs](https://tripss.github.io/nestjs-query/docs/graphql/resolvers/#custom-endpoints).

You still need to add:
```ts
  NestjsQueryGraphQLModule.forFeature({
      imports: [NestjsQueryTypeOrmModule.forFeature([TodoItemEntity])],
      assemblers: [TodoItemAssembler],
      resolvers: [
        {
          DTOClass: TodoItemDTO,
          EntityClass: TodoItemEntity,
        },
      ],
    }),
```
```ts
@Module({
  exports: [],
  imports: [
    NestjsQueryGraphQLModule.forFeature({
      imports: [TypeOrmModule.forFeature([MarkdownActivity])],
      services: [MarkdownActivityService],
      resolvers: [
        {
          DTOClass: YourDTO,
          EntityClass: MarkdownActivity,
        },
      ],
    }),
  ],
  providers: [
    MarkdownActivityResolver,
  ],
})
export class MarkdownModule {}
```

**Comment by xin-ze** [comment]
@TriPSs  Thank you, I have one more question: do I have to declare a DTO class? There is no such concept in the demo code. After rewriting it like this, the error is still reported.
<img width="1128" alt="image" src="https://github.com/TriPSs/nestjs-query/assets/16400882/3f69425f-3826-4e8c-aafd-a0677628977e">

<img width="1200" alt="image" src="https://github.com/TriPSs/nestjs-query/assets/16400882/bebc99ed-6404-4bcb-b860-46845521a62e">
