### ISSUE TITLE
Error: No fields found to create FilterType.

### ISSUE THREAD

**Issue by xin-ze** [TriPSs/nestjs-query#232]
**Describe the bug**

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

yes

**To Reproduce**
1. clone the small reproducible demo repository: [https://github.com/xin-ze/nestjs_reproduction/tree/main](https://github.com/xin-ze/nestjs_reproduction/tree/main)
2. select 'main' branch
3. refer to README.md and execute the code

**Expected behavior**
This error disappears

**Screenshots**
<img width="1500" alt="image" src="https://github.com/TriPSs/nestjs-query/assets/16400882/f76a0839-0968-48c7-bfad-0f03b5e7b421">

code path: apps/content/src/app/markdown/markdown.module.ts
<img width="1025" alt="image" src="https://github.com/TriPSs/nestjs-query/assets/16400882/e52944a5-50cf-4107-a04e-25d0f2b2f82c">

**Desktop (please complete the following information):**
 - Node Version:  18.16.0
 - Nestjs-query Version v3.0.0

**Additional context**

**Comment by TriPSs** [comment]
Hi, checking on my phone but you don't seem to have read the basic examples in the docs as you are providing the entity as a dto. Please read the docs.

**Comment by xin-ze** [comment]
@TriPSs  DTO does not exist in my project. Is there any sample code for this scenario?  Thanks!
