### ISSUE TITLE
Specified relationName is not honoured for mutations and aggregations

### ISSUE THREAD

**Issue by coupster74** [TriPSs/nestjs-query#239]
**Describe the bug**
When a relationship name is specified in the definition, in v5.1.0-alpha.1 it appears to be working on the entity results (wasn't in the ^4.0.0 version I was using before). However, aggregate functions are still being pluralized and the relationship name is not being used

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

yes

**To Reproduce**
1) for a relationship, specify the name, example below: 

```
@FilterableUnPagedRelation('ofInterestTo', () => Company, {
  relationName: 'ofInterestTo',
  nullable: true,
  update: { enabled: true },
  remove: { enabled: true },
})
```

when you view the fields available, you see aggregate results are not honoring the relationship name: 
![image](https://github.com/TriPSs/nestjs-query/assets/6988322/688ec223-e8bf-49b9-a21f-76b952156fae)

nor are the resulting mutations: 
![image](https://github.com/TriPSs/nestjs-query/assets/6988322/34740840-ba08-4289-b247-6171b729d80c)

**Expected behavior**
Mutations and aggregate graphql attributes/objects should also adhere to the relationship name specified. 

**Desktop (please complete the following information):**
 - Node Version v18.14.0
 - Nestjs-query Version: 5.0.0-alpha.1

**Comment by TriPSs** [comment]
Thanks for reporting, I see I only updated the read relations resolver and not the others.
