### ISSUE TITLE
The inferred type of X cannot be named without a reference to '@ptc-org/nestjs-query-graphql/node_modules/@ptc-org/nestjs-query-core'. This is likely not portable. A type annotation is necessary

### ISSUE THREAD

**Issue by GP4cK** [TriPSs/nestjs-query#24]
When extending a resolver to override some methods, I have the following error:  
`The inferred type of X cannot be named without a reference to '@ptc-org/nestjs-query-graphql/node_modules/@ptc-org/nestjs-query-core'. This is likely not portable. A type annotation is necessary`

Here's a code sample:

```ts
@Resolver()
export class NotificationResolver extends ReadResolver(Notification, { one: { disabled: true } }) {
                ^^^^^^^^^^^^^^^^^^^ The inferred type of [...]
  constructor(
    private readonly notificationService: NotificationService,
  ) { super(notificationService); }
  // ...
}

```

To solve it, I had to add this to my tsconfig.json:

```json
{
  "compilerOptions": {
    // Other stuff...
    "baseUrl": "./",
    "paths": {
      "@ptc-org/nestjs-query-graphql/node_modules/@ptc-org/nestjs-query-core": ["node_modules/@ptc-org/nestjs-query-core/"],
    },
  },
}

```

I believe there is some linking missing in the library but I don't know where to start looking to solve this issue...

**Comment by TriPSs** [comment]
Aah good catch, will check it out.

Did not have this in my own applications because I have all the nestjs-query packages in resolutions, forcing only that one version.

**Comment by TriPSs** [comment]
This should no longer be an issue with the latest alpha releases.
