### ISSUE TITLE
Filtering for OR in TypeORM and GraphQL results in AND

### ISSUE THREAD

**Issue by Justin99b** [TriPSs/nestjs-query#250]
**Describe the bug**
When trying to query an Entity using the "or" filter the final SQL query uses AND instead of OR

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes

**To Reproduce**
1. Create a Entity
2. Query that Entity with the or filter

**Expected behavior**
OR should be applied instead of AND

**Screenshots**

**Desktop (please complete the following information):**
 - Node Version: 8.15.0
 - Nestjs-query Version: 6.1.0

**Additional context**
I think the issue lays in the `where.builder.ts` in the TypeORM implementation.
I have tried to fix it but its impossible for me to debug this.
Since i cant link the NX project to my project i have trying around to recompiling and replacing the files.

Tested this a fair bit and can say the following things;

`withFilterComparison` and `withRelationFilter` both uses a hardcoded AND to filter.

It goes in recursivly and builds the Or's correct i think but then just uses AND in the end anyways

Really would appreacheate the help and would be happy to make a pull request if im able to fix this

p.s Thank you for maintaning this masterpiece of productivity <3

**Comment by TriPSs** [comment]
Could you add a example with this issue? Than I will take a look.

**Comment by Justin99b** [comment]
Well i just found the issue after all that time

Turns out this is wrong and results in a AND
```
"filter": {
    "or": {
      "label": {
        "eq": "XYZ"
      },
      "tags": {
        "label": {
          "eq": "red"
        }
      },
    }
  }
```
and this is correct and reults in the correct OR

```
"filter": {
    "or": [
      {
        "label": {
          "eq": "XYZ"
        }
      },
      {
        "tags": {
          "label": {
            "eq": "red"
          }
        }
      }
    ]
  }
```

Apollo Studio said i could use both. I dont know if i just overseen it in the docs or if there really isnt a example for graphql how to write the query for the filters and i just assumed it worked like every other.

Anyways, Isn't this still technically a bug? even when having the OR there (in the first example) it still uses a AND instead of a OR

**Comment by TriPSs** [comment]
> Isn't this still technically a bug

No I don't think so, users have the option to provide multiple filters inside the `OR`, if for example that would mean that everything inside that filter becomes `OR` you will never be able to create filters like this:
```
SELECT * FROM foo WHERE (a = B) OR (a = C AND b = C)
```
So if you want to do multiple or statements after each other you should provide multiple items inside the `or` array.

Maybe it's indeed a good idea to [extend the docs](https://tripss.github.io/nestjs-query/docs/concepts/queries#filter-reference) with examples on how to properly filter with `AND` `OR`
