### ISSUE TITLE
Implement schema based multi tenancy

### ISSUE THREAD

**Issue by piyushhanchate** [TriPSs/nestjs-query#251]
I've been trying to implement schema based multi tenancy using [this](https://thomasvds.com/schema-based-multitenancy-with-nest-js-type-orm-and-postgres-sql/) guide, it requires me to inject a custom request scoped connection in the services. Could you help me out with implementing this, please?

**Comment by TriPSs** [comment]
I have no experience with multi tenancy.

**Comment by GP4cK** [comment]
We managed to get it to work by doing this:

<details>
<summary>
Step 1: Create a `TypeOrmConfigService` that extends `TypeOrmOptionsFactory` in which you inject the request to extract the tenant id.
</summary>

```ts
import { Inject, Injectable } from '@nestjs/common';
import { DataSource, DataSourceOptions } from 'typeorm';
import { REQUEST } from '@nestjs/core';
import { TypeOrmModuleOptions, TypeOrmOptionsFactory } from '@nestjs/typeorm';
import type { Request } from 'express';

@Injectable()
export class TypeOrmConfigService implements TypeOrmOptionsFactory {

  private databaseID: string;

  constructor(@Inject(REQUEST) readonly req: Request ) {
    this.databaseID = /* Extract the databaseID/tenantID from the request */;
  }

  createTypeOrmOptions(): TypeOrmModuleOptions {
    return {
      ...yourBaseOrmConfig,
      database: this.databaseID,
    };
  }

  static async getOrCreateDataSource(options?: DataSourceOptions): Promise<DataSource> {
    /** Create and initialize the DataSource here. */
  }
}
```
</details>

<details>
<summary>Step 2: in your `app.module.ts`, use TypeOrm.forRootAsync with the service you created.</summary>

```ts
import { Module, NestModule } from "@nestjs/common";
import { TypeOrmModule } from "@nestjs/typeorm";
import { TypeOrmConfigService } from "./config/TypeORMConfig.service";

@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      useClass: TypeOrmConfigService,
      dataSourceFactory: (options) => TypeOrmConfigService.getOrCreateDataSource(options),
    }),
    // Other imports
  ],
})
export class AppModule implements NestModule {}
```
</details>

And you should be good to go. Now when you inject a repository in your services with `@InjectRepository()`, they automatically become request-scoped and use the right connection.
