### ISSUE TITLE
How to Implement Login Route and Secure Routes with JWT Bearer Authentication? 

### ISSUE THREAD

**Issue by daniloras** [TriPSs/nestjs-query#263]
Hi, 

I need to implement a login route, but I'm unsure how to proceed using the library https://tripss.github.io/nestjs-query.

I'd like guidance on how to create a login route using the mentioned library, including any necessary configurations or best practices.

I also need assistance on how to secure my routes using JWT Bearer authentication once the login route is implemented. Any examples or documentation references would be appreciated.

**Comment by TriPSs** [comment]
Sorry but this does not seem really related to this library, please just follow the [NestJS docs](https://docs.nestjs.com/security/authentication).
