### ISSUE TITLE
Enable algolia search

### ISSUE THREAD

**Issue by GP4cK** [TriPSs/nestjs-query#27]
## 📚 Documentation

This issue is a request to enable the algolia search on the documentation, like on the original repo.
It's super useful to navigate the documentation.

### Have you read the [Contributing Guidelines on issues](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes

**Comment by TriPSs** [comment]
I have actually requested it but they said it was already on even though I did not receive a token yet, will contact them again.

**Comment by TriPSs** [comment]
FYI: Emailed them again, they keep saying I already received the credentials but sadly I did not.

**Comment by GP4cK** [comment]
Maybe they are confusing with the original repo(?)

**Comment by TriPSs** [comment]
Think so, I reapplied again and this time answered all the questions and pointed that out directly.
