### ISSUE TITLE
`unmet peer graphql-subscriptions@^2.0.0: found 3.0.0`

### ISSUE THREAD

**Issue by kasir-barati** [TriPSs/nestjs-query#327]
**Describe the bug**
So it is not really a bug but can become one since graphql-subscriptions have changed their API since version 3.x.

https://github.com/apollographql/graphql-subscriptions/blob/master/CHANGELOG.md#300

`asyncIterator` is no longer available, instead `asyncIterableIterator` is the one that should be used.

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

Yep

**To Reproduce**
1. Create a new NestJS project
2. ```shell
    pnpm add @ptc-org/nestjs-query-core @ptc-org/nestjs-query-graphql @ptc-org/nestjs-query-typeorm @nestjs/typeorm @nestjs/common @nestjs/graphql graphql graphql-subscriptions class-transformer class-validator dataloader typeorm
    ```
Then you can see this warning:
```shell
 WARN  Issues with peer dependencies found
.
└─┬ @ptc-org/nestjs-query-graphql 7.1.0
  └── ✕ unmet peer graphql-subscriptions@^2.0.0: found 3.0.0
```

**Expected behavior**
No warning

**Screenshots**
![image](https://github.com/user-attachments/assets/d9a71f21-c954-4ba9-826f-256d3be78917)

**Desktop (please complete the following information):**
 - Node Version: 22.12.0
 - Nestjs-query Version: 7.1.0

**Additional context**

I am currently working with this monorepo project inside a bigger repo: https://github.com/kasir-barati/nestjs-materials/tree/main/typeorm

**Comment by TriPSs** [comment]
Thanks, would you be willing to create a PR?

**Comment by kasir-barati** [comment]
Yeah sure. Why not. BTW thanks for this wonderful work. It is really good that we have still this lib kicking.

**Comment by kasir-barati** [comment]
@TriPSs  I am not familiar with the release plan, do yo think you can tell me how usually new releases are published on npm, if we have a doc for I'd love to take a look.

**Comment by TriPSs** [comment]
Useally I realse when there is something to release, now I did all the dependa bot things and went for food and forgot it 😅, let me release this.
