### ISSUE TITLE
Broken link in the doc

### ISSUE THREAD

**Issue by kasir-barati** [TriPSs/nestjs-query#344]
## 📚 Documentation

Here: https://tripss.github.io/nestjs-query/docs/concepts/queries#paging

The link to "issue" is broken.

> When using filters on relations with typeorm in combination with paging, performance can be degraded on large result sets. For more info see this [issue](https://github.com/tripss/nestjs-query/issues/954)

Dunno where should it be pointing to. Any comment?

### Have you read the [Contributing Guidelines on issues](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

Yup.

**Comment by kasir-barati** [comment]
If you know where it is doing the magic of adding default sort since I was unable to find any trace of it. I tried to debug it but it was like a maze and I could not find it :sweat_smile:.

**Comment by TriPSs** [comment]
The link of the "issue" should be https://github.com/doug-martin/nestjs-query/issues/954, think is became broken when I replaced all references to that repo to this one.

**Comment by kasir-barati** [comment]
Aha, OK. I will then take care of it in another PR. BTW could please gimme some pointers about pagination in nestjs-query? it is kinda like a mystery to me since I thought that I am using cursor based pagination (meaning I was expecting more or less a query like this: `SELECT * FROM tbl WHERE id > cursor.id ORDER BY id ASC`) but what I saw in terminal was this:

```sql
SELECT
    "Alert"."id" AS "Alert_id",
    "Alert"."title" AS "Alert_title",
    "Alert"."description" AS "Alert_description",
    "Alert"."userId" AS "Alert_userId",
    "Alert"."alertTypeId" AS "Alert_alertTypeId",
    "Alert"."createdAt" AS "Alert_createdAt",
    "Alert"."updatedAt" AS "Alert_updatedAt"
FROM "alert" "Alert"
LIMIT 7
OFFSET 6 # From where this 6 comes? I speculate that nestjs-query is either storing the keys and their offset in DB or just fetch it right when I send the query. But the problem is that I cannot see that in PostgreSQL logs. Or maybe it is part of the cursor???
```

When I send this query:

```graphql
query {
  alerts(paging: {
  "paging": {
    "first": 6,
    "after": "YXJyYXljb25uZWN0aW9uOjU="
  }
}) {
    edges {
      cursor
      node {
        id
        title
        createdAt
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      startCursor
      hasPreviousPage
    }
  }
}
```

Any comment would be much appreciated @TriPSs :pray:.

**Comment by kasir-barati** [comment]
> The link of the "issue" should be [doug-martin/nestjs-query#954](https://github.com/doug-martin/nestjs-query/issues/954), think is became broken when I replaced all references to that repo to this one.

Hmmm, it's interesting. CHange log says that this is not a bug anymore: https://github.com/kasir-barati/nestjs-query/blob/master/CHANGELOG.md#bug-fixes-39

**Comment by kasir-barati** [comment]
[Here](https://tripss.github.io/nestjs-query/docs/graphql/dtos#allowed-boolean-expressions) it seems that we have a contradiction:

First docs says: 

![In this example we will only allow and expressions](https://github.com/user-attachments/assets/c6b1ee2c-d5b0-4c03-94e5-a656d0127bf3)

And then just couple of paragraph further we have:

![and disable all and/or boolean expressions](https://github.com/user-attachments/assets/29016058-1a00-45e1-aeb4-f1951a0b70b0)

I believe it should be "and disable all `and` boolean expressions."

**Comment by kasir-barati** [comment]
Another place that the docs seems a bit off is when [it says](https://tripss.github.io/nestjs-query/docs/graphql/queries/endpoints#querying): 

> By default if you do not provided an arguments you can query for all records.

But [earlier](https://tripss.github.io/nestjs-query/docs/graphql/dtos#result-page-size) it said:

> By default all results will be limited to 10 records.

It just confused me and I tried it out in my local machine and it was returning only the first 10 records. So I suggest this wording:

"By default if you do not provided an arguments it will uses the [default value specified for page size](https://tripss.github.io/nestjs-query/docs/graphql/dtos#result-page-size)."
