### ISSUE TITLE
Version incompatibility with NestJS 

### ISSUE THREAD

**Issue by kmcgahee** [TriPSs/nestjs-query#39]
**Describe the bug**

Hi @TriPSs,

First, I want to say thank you for continuing to maintain this project. 

My issue is that I can't find a consistent set of versions to get it to install correctly. I run into an impossible case.

My existing project is using the newest version of Nest ("@nestjs/graphql": "^10.0.0")

But this package (your fork of nestjs-query) says that it requires 

"@nestjs/graphql": "^9.0.0"

which itself requires 

"graphql": "^15.0.0" 

(instead of graphql 16 which is what the newest version of Nest uses).

So I tried to downgrade all my Nest packages to the following versions:

```
    "@nestjs/apollo": "^9.0.0",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/graphql": "^9.0.0",
    "@nestjs/passport": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/typeorm": "^8.0.1",
    "@ptc-org/nestjs-query-graphql": "^1.0.1",
    "@ptc-org/nestjs-query-sequelize": "^1.0.1",
    "apollo-server-express": "^3.10.1",
    "class-transformer": "^0.5.1",
    "graphql": "^15.0.0",
```

But then I get the error that
 @apollo/gateway@2.1.1
which is used by your package:
@ptc-org/nestjs-query-graphql@"^1.0.1" 
requires
graphql@"^16.5.0"

But... I can't use graphql 16 (see my comment above about having to use 15).

So I'm not sure where to go to get this working, since I seem to be stuck in a circle.

Do you have a stable set of package versions from your personal project(s) that you could share so that I can get this up and running?

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

Yep! 

**To Reproduce**
Install the packages mentioned above and note the peer dependency issues.

**Expected behavior**
I expected that when downgrading NestJS to use the peer dependencies required by this project (i.e.  "graphql": "^15.0.0" ) that then the other peer dependency of  @apollo/gateway@2.1.1 wouldn't complain about needing graphql 16.

**Desktop (please complete the following information):**
 - Node Version: 16.17.0
 - Npm: 15.8.0
 - Nestjs-query Version: @ptc-org/nestjs-query-graphql@"^1.0.1" 

**Additional context**
I tried the --legacy-peer-deps options from npm but encountered errors when trying to run nest, so that short-term workaround doesn't seem possible.

**Comment by Goopil** [comment]
I'm running a project with "@nestjs/graphql": "^10.0.0" & graphql 16.

For the ref I'm using pnpm. I had to set 
legacy-peer-deps=false for it to stop complaining.

Maybe this work with npm too.

PS no problem so far.

PS2 nestjs/graphql 10+ introduce mercurius support. Has the package is not yet fully compatible. The constrained version is downscaled. If you stick to Apollo server, you normally won't have any strange behaviors.

Cheers

**Comment by TriPSs** [comment]
Have the same as @Goopil, running with no issues on `@nestjs/graphql` version 10, I will update the peer deps.

FYI: We updated a lot (like, a lot) of deps and the peer deps where forgotten to be updated, sorry for this.

**Comment by kmcgahee** [comment]
Awesome, thanks @Goopil and @TriPSs. I really appreciate the quick response. Everything is running great now.

**Comment by Goopil** [comment]
Glad to read it. Gl hf for your project !
