### ISSUE TITLE
Exposing pubSub through services and resolvers

### ISSUE THREAD

**Issue by nickmanks** [TriPSs/nestjs-query#45]
It would be absolutely fantastic if the underlying CRUDResolver and matching ORM service could expose the pubSub api nicely.  Right now its hidden and hard to use in a custom fashion, it also will add `JSON.stringify(authorizationFilter)` to the publish event name sometimes, not entirely sure how or why this is?

e.g. (pseudo-code)

In resolver:
```ts
@Resolver(() => SomeDto)
export class SomeDtoResolver extends CRUDResolver(SomeDto, {
  enableSubscriptions: true,
}) {
  constructor(
    private readonly someService: SomeService,
    @InjectPubSub() override readonly pubSub: PubSub,
  )

  @Mutation(() => Boolean)
  async customUpdate(@Args() { id, update }: UpdateVariables) {
    const updated = await this.update(id, update);
    await this.publishUpdatedOneEvent(updated);
  }
}
```

It would also be great if there was way to publish events easily from services too, so that custom business logic outside the crud resolvers can still hook into publishing updated events

**Comment by TriPSs** [comment]
I think the `JSON.stringify(authorizationFilter)` is added to make sure that if you subscribe with certain auth filters you will only get back the events that have the same ones.

The functions like `publishUpdatedOneEvent` are available to be used right? Think as a starting point it's a good idea to add those to the documentation for better visibility.

**Comment by nxmad** [comment]
@TriPSs authorizationFilter is lost for deleteOne mutation. When you subscribe to channel, it contains just event name without filters, however event is published to another channel with authfilter, so you will never get event from subscription. Please let me know if you fixed this behaviour in your fork. Or do you have any list of fixes you did?

**Comment by TriPSs** [comment]
Think this ticket was solver with #64
