### ISSUE TITLE
Issue with types missing, possibly incorrectly published package???

### ISSUE THREAD

**Issue by smolinari** [TriPSs/nestjs-query#48]
I'm getting back to my project after several months and I'm bogged down with a couple of issues from `nestjs-query-typegoose` and to be honest, I'm not sure it's just my incompetence or what. 

At any rate, this error is happening while building/ compiling: 

src/user/user.module.ts(2,44): error TS7016: Could not find a declaration file for module '@ptc-org/nestjs-query-typegoose'. '/home/scott/Documents/tmp/m8a-new/common/temp/node_modules/.pnpm/@ptc-org+nestjs-query-typegoose@1.1.0_aefggeysizmixjxhkqtfgu72mu/node_modules/@ptc-org/nestjs-query-typegoose/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ptc-org__nestjs-query-typegoose` if it exists or add a new declaration (.d.ts) file containing `declare module '@ptc-org/nestjs-query-typegoose';`

This happens when I have `strict: true` set. If I set it to "off", the build goes through with no errors, but then I get this error while running my app:

Error: Cannot find module './module'
Require stack:
- /home/scott/Documents/tmp/m8a-new/common/temp/node_modules/.pnpm/@ptc-org+nestjs-query-typegoose@1.1.0_aefggeysizmixjxhkqtfgu72mu/node_modules/@ptc-org/nestjs-query-typegoose/src/index.js
- /home/scott/Documents/tmp/m8a-new/packages/core/dist/user/user.module.js
- /home/scott/Documents/tmp/m8a-new/packages/core/dist/auth/auth.module.js
- /home/scott/Documents/tmp/m8a-new/packages/core/dist/auth/index.js
- /home/scott/Documents/tmp/m8a-new/packages/core/dist/index.js
- /home/scott/Documents/tmp/m8a-new/packages/starter-kit-api/dist/app.module.js
- /home/scott/Documents/tmp/m8a-new/packages/starter-kit-api/dist/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Function.Module._load (node:internal/modules/cjs/loader:803:27)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/scott/Documents/tmp/m8a-new/common/temp/node_modules/.pnpm/@ptc-org+nestjs-query-typegoose@1.1.0_aefggeysizmixjxhkqtfgu72mu/node_modules/@ptc-org/nestjs-query-typegoose/src/index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Function.Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)

It's like the package wasn't built properly to begin with??? 

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes

**To Reproduce**

Don't have any reproduction repo. Sorry. If it is a prerequisite, let me know. 

**Expected behavior**
I'm expecting none of these errors. 

**Desktop (please complete the following information):**
 - Node Version: 18.9.0
 - Nestjs-query Version: 1.1.0

I hope you can help me on this, as it's blocking any further work. Thanks!

Scott

**Comment by TriPSs** [comment]
I think there are indeed some publishing issues with Typegoos, thought I fixed those but will check it out. Will also check the any it's complaining about.

**Comment by smolinari** [comment]
Awesome.... thank you! @TriPSs 

Scott

**Comment by smolinari** [comment]
@TriPSs - When do you think you can get to this or have you started working on it? I have a bit of time and can try myself to get the Typegoose  package up-to-date. 

Scott

**Comment by TriPSs** [comment]
@smolinari that would be awesome! The earliest for me would be the end of next week.

**Comment by smolinari** [comment]
@TriPSs - Ok. I'm giving it a shot. It looks like everything builds and tests ok. I also upped the deps as in the PR I wrote. 

I think the issue must be in how you published the package to npm. 

I noticed in the `package.json` of `query-typegoose` the following setting is different than in the other packages:

```
  "files": [
    "dist/src/**"
  ],
  ```
  Everywhere else it is:
  
  ```
    "files": [
    "src/**"
  ],
  ```
  I think that is the culprit, maybe?

Scott

**Comment by TriPSs** [comment]
Makes sense indeed

**Comment by TriPSs** [comment]
Makes sense indeed

**Comment by smolinari** [comment]
@TriPSs - Any chance you could re-publish the `query-typegoose` package if I post a PR with the changes?

Scott
