### ISSUE TITLE
Keycloak support

### ISSUE THREAD

**Issue by Memo99** [TriPSs/nestjs-query#61]
**Is your feature request related to a problem? Please describe.**
I can't use the nest-keycloak-connect decorators on my DTO classes. 

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

yes

**Describe the solution you'd like**
Either support how to use the nest-keycloak-connect library with nestjs-query or how to write a authenticator for keycloak.

**Comment by TriPSs** [comment]
Could you elaborate a bit more as i'm not know with `nest-keycloak-connect`? I see it uses normal guards so why would it not work?

**Comment by Memo99** [comment]
For example the @Public Guard is not working when directly adressing the DTO. So every query or mutation needs authentication. 

And building for every Module a Resolver is a bit tricky with those filtering and sorting mechanisms. I'm now sitting since 3 days on this topic and don't know how to solve it correctly :(

**Comment by TriPSs** [comment]
If I understand correctly then you would like to make a endpoint public right? If correct then could you try the following in the  module:
```
read: {
      one: { description: 'Get one xx.' },
      many: { description: 'Get all xx.' },
      decorators: [
        Public()
      ]
    },
```

**Comment by Memo99** [comment]
It worked! You are my hero. Many thanks for you support and good work!
