### ISSUE TITLE
Add an extra query/parameter to fetch without pagination

### ISSUE THREAD

**Issue by ValentinVignal** [TriPSs/nestjs-query#62]
**Is your feature request related to a problem? Please describe.**

Most of the time I was to fetch my data in a paginated way, so I'm don't want to use 

```ts
@QueryOptions({ pagingStrategy: PagingStrategies.NONE })
```

But in some specific scenarios, I don't want to have paginated data but I want to fetch the entire list.
I cannot reuse the generated queries as they require `paging.first` to be not `null` and `>1`

For example, the generated query would be:

```graphql
type Query {
  users(
    """Limit or page results."""
    paging: CursorPaging = {first: 10}

    """Specify to filter the records returned."""
    filter: UserFilter = {}

    """Specify to sort results."""
    sorting: [UserSort!] = []
  )
}

input CursorPaging {
  """Paginate before opaque cursor"""
  before: ConnectionCursor

  """Paginate after opaque cursor"""
  after: ConnectionCursor

  """Paginate first"""
  first: Int

  """Paginate last"""
  last: Int
}
```

Because of that, I have to create a custom `@Query`.

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?
 
Yes

**Describe the solution you'd like**

It would be nice to create an un-paginated query or support `paging.first` being `null` (or whatever other solution) to fetch the unpaginated list of records.

**Describe alternatives you've considered**

I'm creating a new query end point by hand.

**Comment by GP4cK** [comment]
Have you tried something like this:

```ts
NestjsQueryGraphQLModule.forFeature({
  imports: [TodoModule],
  resolvers: [
    {
      // Assuming Todo is decorated with `@QueryOptions({ pagingStrategy: PagingStrategies.NONE })`
      DTOClass: Todo,
      EntityClass: Todo,
      // ...
    },
    {
      DTOClass: Todo,
      EntityClass: Todo,
      pagingStrategy: PagingStrategies.CURSOR,
      read: {
        // Give a custom name to not conflict with the first resolver.
        many: { name: 'todoPaginated' },
      },
      // ...
    },
  ],
}),
```

**Comment by ValentinVignal** [comment]
Thanks @GP4cK , that did it
