### ISSUE TITLE
Delete subscription not working

### ISSUE THREAD

**Issue by windose** [TriPSs/nestjs-query#64]
**Describe the bug**

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes

**To Reproduce**
1. Enable subscriptions in resolver
2. Subscribe to deletedOne or deletedMany
3. Trigger a deleteOne or deleteMany mutation

**Expected behavior**
The subscription should trigger if an object was deleted.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Node Version: 14.14.0
 - Nestjs-query Version: 1.1.2

**Additional context**
The other subscriptions, like updated and created are working fine, but deleted not.

**Comment by nxmad** [comment]
I can confirm this, AuthFilter is lost for delete subscriptions. Mentioned 13 days ago at #45. @TriPSs please merge.

**Comment by TriPSs** [comment]
This is fixed thanks to @windose ❤️  Released in version v1.1.3
