### ISSUE TITLE
Name is not changed in the generated schema

### ISSUE THREAD

**Issue by AmrAnwar** [TriPSs/nestjs-query#68]
**Describe the bug**

Names don't get changed in Graphql schema, although name parameter was set in `@FilterableField` and `@Field`

**To Reproduce**
Here for example I change the `name` but it doesn't change
```typescript
import { ArgsType, Field, Int, ObjectType } from '@nestjs/graphql';
import {
  FilterableField,
  QueryArgsType,
} from '@ptc-org/nestjs-query-graphql';

@ObjectType()
class MyObject:
  @FilterableField({ allowedComparisons: ['eq', 'like', 'notLike'], name: 'ip_address' })
  @Field({ name: 'ip_address', nullable: true })
  ipAddress?: string;


@ArgsType()
export class MyObjectQuery extends QueryArgsType(MyObject) { }
```

**Expected behavior**
name should be changed to `ip_address` but I get the typescript name `ipAddress`

**Desktop (please complete the following information):**
 - Node Version v16.13.2
  "@ptc-org/nestjs-query-core": "^1.1.4",
  "@ptc-org/nestjs-query-graphql": "^1.1.4",

**Comment by TriPSs** [comment]
Could you elaborate a bit more? I added a [test case](https://github.com/TriPSs/nestjs-query/pull/69) to check this but I cannot reproduce.

**Comment by TriPSs** [comment]
Going to close, if this is still a issue please reopen!
