### ISSUE TITLE
Error: Id cannot be specified when updating

### ISSUE THREAD

**Issue by IvoneDjaja** [TriPSs/nestjs-query#75]
**Describe the bug**
When I call mutation `updateOneItem`, I get this error `Error: Id cannot be specified when updating`. If I remove the `id` from the argument, graphQL produces this error `Field \"id\" of required type \"ID!\" was not provided`.

```
Module({
  imports: [
    NestjsQueryGraphQLModule.forFeature({
      imports: [NestjsQueryTypeOrmModule.forFeature([UserRole])],
      resolvers: [
        {
          DTOClass: UserRole,
          EntityClass: UserRole,
          UpdateDTOClass: UserRoleInput,
          create: {
            disabled: true,
          },
          update: {
            many: {
              disabled: true,
            },
          },
          delete: { disabled: true },
          pagingStrategy: PagingStrategies.NONE,
        },
      ],
    }),
  ],
  providers: [UserRoleService, UserRoleResolver],
  exports: [UserRoleService, UserRoleResolver],
})
export class UserRoleModule {}
```

```
type Mutation {
  updateOneUserRole(input: UpdateOneInput!): UserRole!
}

input UpdateOneInput {
  """The id of the record to update"""
  id: ID!

  """The update to apply."""
  update: UserRoleInput!
}

input UserRoleInput {
  deleted: Float
  id: ID
  name: String!
  description: String
  download: DownloadTypes!
  adminConsole: Float!
  manageSubscription: Float!
  createProject: Float = 0
}
```

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes.

**To Reproduce**
1. Step 1
2. Step 2

**Expected behavior**
It updates successfully without error.

**Screenshots**

**Desktop (please complete the following information):**
 - Node Version [v16.1.3.0]
 - Nestjs-query Version [9.1.2]

**Additional context**

**Comment by GP4cK** [comment]
Have you tried removing `id` from the class definition of `UserRoleInput`?

**Comment by ValentinVignal** [comment]
@IvoneDjaja it is a bit hard to understand how your schema is generated and to help you since I don't know what is `UseRole` or `UserRoleInput`.
If you want to customize the schema input type for "update one", have you looked into https://tripss.github.io/nestjs-query/docs/graphql/types#updateoneinputtype ?

You can check out https://github.com/ValentinVignal/reproducible/tree/ptc-org/nestjs-query/custom-update-and-create-types for an example from the getting started tutorial of https://tripss.github.io/nestjs-query/docs/introduction/example

**Comment by IvoneDjaja** [comment]
> https://tripss.github.io/nestjs-query/docs/introduction/example

I tried that, but the error persists, I don't think it is coming from `id` in `UserRoleInput`
